name: ini generate
run-name: ${{ github.actor }} generating ini files
on:
  push:
    branches:
      - "main"
    paths:
      - configs/**

jobs:
  generate-ini:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%s')"
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - uses: carvel-dev/setup-action@v2
        with:
          only: ytt
      - run: python -m pip install -r scripts/requirements.txt
      - run: python scripts/generate.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: "config-update-${{ steps.date.outputs.date }}"
          commit_message: push application deployment to dev
          commit_user_name: github_action
          create_branch: true
          repository: .
      - name: create pull request
        run: gh pr create --repo ${{github.repository}} -B main -H dev-${{steps.date.outputs.date}} --title 'config update' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}