name: ini generate
run-name: ${{ github.actor }} generating ini files
on:
  push:
    branches:
      - "main"
    paths:
      - configs/**

jobs:
  generate-ini:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - uses: carvel-dev/setup-action@v2
        with:
          only: ytt
      - run: python scripts/generate.py
          